static void initScene0(void);
static void renderHeader0(void);
static void renderTimeInterface(void);
static void renderTouchInterface(void);
static void renderJoystickInterface(void);
static void renderGyroInterface(void);
static void renderSliderInterface(void);
static void renderFirmwareInterface(void);
static void compileInterfaces(void);
static void buildScene0(float size);
static void exitScene0(void);
